### ISSUE TITLE
How to import the library?

### ISSUE THREAD

**Issue by horahh** [Rogdham/bigxml#2]
I did not know how to import lib, did not find how in the documentation, had to look in the unit tests to find out.

**Comment by Rogdham** [comment]
Hello, you are right!

Something like the following will be added in the next version of the documentation.

---

The most used imports are the following:

```python
from bigxml import Parser, xml_handle_element, xml_handle_text
````

If you want to catch [exceptions](https://bigxml.rogdham.net/exceptions) raised by this module:

```python
from bigxml import BigXmlException
````

For [type hints](https://bigxml.rogdham.net/typing):

```python
from bigxml import HandlerTypeHelper, XMLElement, XMLText
````

**Comment by horahh** [comment]
looks great! thanks

**Comment by Rogdham** [comment]
This can now be found [in the documentation](https://bigxml.rogdham.net/#imports)!

**Comment by horahh** [comment]
BTW, great library, I used it for pretty bit parsing with reduced memory system and worked like a charm!
